version: "3.8"

services:
  api:
    container_name: api
    build:
        context: .
        target: api
    networks:
        martzcodes:
  frontend:
    container_name: frontend
    build:
        context: .
        target: frontend
    ports:
      - 80:80
      - 3333:3333
    networks:
        martzcodes:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

volumes:
  progresDB:
